#!/usr/bin/env bash
# PreToolUse Edit|Write guard for generated pipeline artifacts and the
# source-of-truth spec docs — SailCommand #274 (extracted from the inline
# one-liner it replaces; the specs `ask` branch is unchanged from before).
#
# ---------------------------------------------------------------------------
# INTENT (the acceptance criterion #274 asks be stated next to the guard):
#
# app/public/{data,icons,brand}/ are committed BUILD OUTPUTS produced by
# pipeline/ scripts (npm --prefix pipeline run polars|harbors|mask|icons),
# and app/public/THIRD-PARTY-NOTICES.txt is a committed build output produced
# by an app-side script (npm --prefix app run notices). None of these five
# locations has a legitimate hand-edit workflow: every file under them is
# meant to be regenerated, never typed by hand or patched in place. This
# guard's job is "don't hand-edit a generated artifact", not "these paths
# may never change" — regenerating via the script and committing the result
# is unaffected, since only Claude's own Edit/Write tool calls hit this hook.
#
# ---------------------------------------------------------------------------
# ASYMMETRY (CLAUDE.md, "Design a guard around its ASYMMETRY"): this hook is
# BLOCKING (permissionDecision: "deny"), so it must fail CLOSED — an
# under-fire silently lets a generated artifact drift from its generator,
# which is exactly the defect #274 was filed over (the deny list omitted
# app/public/icons/ and app/public/brand/). Accordingly:
#   - the match below is DIRECTORY-shaped (`*app/public/data/*` etc.), not an
#     enumeration of extensions within those directories — a future pipeline
#     output of any file type is covered automatically;
#   - the original extension patterns (`*.bin`, `*.pmtiles`, `*.pmtiles.png`)
#     are KEPT alongside the directory patterns rather than replaced. Today
#     every file matching them already lives under app/public/data/ (verified
#     via `git ls-files`), which could tempt dropping them as redundant —
#     don't: narrowing a fail-closed guard because of what the CURRENT tree
#     happens to contain is the same reasoning that produced this bug. A
#     future pipeline output of that shape landing OUTSIDE the three known
#     directories stays covered only because these patterns are still here;
#   - the "cannot parse tool input" and "no jq/python3" paths below resolve to
#     `ask` (surface to a human), never to silent allow.
#
# Explicitly NOT covered (residual gaps, not this issue's scope):
#   - app/public/basemap-assets/ (vendored third-party glyph/sprite assets,
#     refreshed via the manual `cp` procedure in pipeline/README.md, not an
#     `npm --prefix pipeline run <script>` output) is deliberately excluded:
#     its OFL.txt/LICENSE.txt license files are the only things ever
#     hand-touched there and must stay writable.
#   - app/public/test-fixtures/wind-sw12.json is deliberately excluded: it is
#     regenerated by `node scripts/gen-wind-fixture.mjs` (app/package.json's
#     `pree2e`), which runs via Bash/npm, never through this Edit|Write hook,
#     so guarding it here would not protect the regeneration workflow anyway
#     — and unlike the five paths above it IS a legitimate hand-adjust target
#     for a deliberate fixture-generator change (CLAUDE.md: "restore it, not
#     commit it" implies routine, not forbidden, edits).
#   - This guard's matcher is `Edit|Write` only. A Bash-mediated write to any
#     of the five guarded paths (`cp`, `sed -i`, a heredoc redirect, a Node
#     script invoked via `node -e`) bypasses it entirely. That gap is larger
#     than the one #274 closes and is out of scope here.
set -u

IN=$(cat)

f=$(printf '%s' "$IN" | jq -r '.tool_input.file_path // empty' 2>/dev/null) \
  || f=$(printf '%s' "$IN" | python3 -c "import json,sys;print(json.load(sys.stdin).get('tool_input',{}).get('file_path') or '')" 2>/dev/null) \
  || {
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"artifact/spec guard cannot parse tool input (jq and python3 unavailable) - protection is inert; install jq."}}'
    exit 0
  }

case "$f" in
  *.bin|*.pmtiles|*.pmtiles.png|*app/public/data/*|*app/public/icons/*|*app/public/brand/*|*app/public/THIRD-PARTY-NOTICES.txt)
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Generated artifact: app/public/{data,icons,brand}/ are committed pipeline outputs (regenerate via npm --prefix pipeline run polars|harbors|mask|icons) and app/public/THIRD-PARTY-NOTICES.txt is a generated dependency manifest (regenerate via npm --prefix app run notices) - never hand-edit, always regenerate."}}'
    ;;
  *docs/superpowers/specs/*)
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask","permissionDecisionReason":"docs/superpowers/specs/ is the user-approved source of truth - CLAUDE.md forbids silently deviating from it. Confirm the user wants the spec itself changed before editing."}}'
    ;;
esac
