import type { Feature, FeatureCollection, MultiLineString } from 'geojson';

/**
 * #629 §1 Q3. Mirrors pipeline/build_contours.py's LEVELS_M — nothing
 * compiles across that Python/TypeScript boundary, so
 * app/src/test/contoursAsset.test.ts pins both against the shipped asset.
 */
export const CONTOUR_LEVELS_M = [2, 3, 5, 10, 15, 20] as const;

/** #629 §1 Q1: the contour basis is the cautious reading. */
export const CONTOUR_BASIS = 'cautious';

export interface ContourLineProperties {
  readonly kind: 'contour';
  readonly levelM: number;
}

export interface NoDataEdgeProperties {
  readonly kind: 'no-data';
}

export type ContourFeature =
  Feature<MultiLineString, ContourLineProperties> | Feature<MultiLineString, NoDataEdgeProperties>;

/**
 * app/public/data/contours.json's shape — generated by
 * pipeline/build_contours.py, never hand-edited (pipeline/README.md).
 */
export interface ContourAsset extends FeatureCollection<
  MultiLineString,
  ContourLineProperties | NoDataEdgeProperties
> {
  readonly maskSha256: string;
  readonly basis: typeof CONTOUR_BASIS;
  readonly toleranceM: number;
  readonly levelsM: readonly number[];
  readonly features: ContourFeature[];
}
