import type { Feature, FeatureCollection, MultiLineString } from 'geojson';

/**
 * #629 §1 Q3. Mirrors pipeline/build_contours.py's LEVELS_M — nothing
 * compiles across that Python/TypeScript boundary, so
 * app/src/test/contoursAsset.test.ts pins both against the shipped asset.
 */
export const CONTOUR_LEVELS_M = [2, 3, 5, 10, 15, 20] as const;

/** #629 §1 Q1: the contour basis is the cautious reading. */
export const CONTOUR_BASIS = 'cautious';

export interface ContourLineProperties {
  readonly kind: 'contour';
  readonly levelM: number;
}

export interface NoDataEdgeProperties {
  readonly kind: 'no-data';
}

export type ContourFeature =
  Feature<MultiLineString, ContourLineProperties> | Feature<MultiLineString, NoDataEdgeProperties>;

/**
 * app/public/data/contours.json's shape — generated by
 * pipeline/build_contours.py, never hand-edited (pipeline/README.md).
 */
export interface ContourAsset extends FeatureCollection<
  MultiLineString,
  ContourLineProperties | NoDataEdgeProperties
> {
  readonly maskSha256: string;
  readonly basis: typeof CONTOUR_BASIS;
  readonly toleranceM: number;
  readonly levelsM: readonly number[];
  readonly features: ContourFeature[];
}

// #629 §3: fetched the first time the toggle turns on, kept in memory
// afterwards — deliberately OUTSIDE loadRoutingAssets()'s Promise.all
// (services/assets.ts), so a failure here can never empty the harbour list
// or block routing (spec §2's "Delivery" paragraph).
//
// Shared module-level state, not component state: the toggle is offered
// from TWO complementary surfaces (DataLayers.tsx's `.depth-legend`,
// RouteLegend.tsx's folded-in `.route-legend-depth`, mirroring the #681
// hatch-toggle precedent) and both must show the SAME fetch/error state —
// the boolean itself already cross-instance-syncs via usePersistedToggle's
// own listener registry; this is that mechanism's sibling for the
// transient (non-persisted) fetch outcome.
export interface ContoursFetchState {
  readonly status: 'idle' | 'loading' | 'loaded' | 'error';
}

let cachedAsset: ContourAsset | null = null;
let cachedPromise: Promise<ContourAsset> | null = null;
let fetchState: ContoursFetchState = { status: 'idle' };
const fetchStateListeners = new Set<(state: ContoursFetchState) => void>();

function setFetchState(next: ContoursFetchState): void {
  fetchState = next;
  fetchStateListeners.forEach((listener) => listener(next));
}

export function getContoursFetchState(): ContoursFetchState {
  return fetchState;
}

export function subscribeContoursFetchState(
  listener: (state: ContoursFetchState) => void,
): () => void {
  fetchStateListeners.add(listener);
  return () => {
    fetchStateListeners.delete(listener);
  };
}

// Already-resolved cache read, for a style-setup callback that must not
// await (installStyleSetup's own contract) — null until loadContoursAsset()
// has resolved at least once.
export function getCachedContourAsset(): ContourAsset | null {
  return cachedAsset;
}

/** Test-only: clears the module cache and fetch state between tests. */
export function __resetContoursForTests(): void {
  cachedAsset = null;
  cachedPromise = null;
  fetchState = { status: 'idle' };
}

/**
 * On-demand fetch, module-cached like services/assets.ts's
 * loadRoutingAssets() — same reset-on-failure shape, so a transient network
 * blip does not permanently wedge every later toggle-on into the same dead
 * promise. Per spec §3 there is no automatic RETRY LOOP; re-arming happens
 * only when a caller invokes this again (e.g. the user toggles off and on).
 */
export function loadContoursAsset(): Promise<ContourAsset> {
  if (cachedAsset) return Promise.resolve(cachedAsset);
  if (cachedPromise) return cachedPromise;
  setFetchState({ status: 'loading' });
  cachedPromise = fetch(`${import.meta.env.BASE_URL}data/contours.json`)
    .then((res) => {
      if (!res.ok) throw new Error(`failed to fetch data/contours.json: HTTP ${res.status}`);
      return res.json() as Promise<ContourAsset>;
    })
    .then((asset) => {
      cachedAsset = asset;
      setFetchState({ status: 'loaded' });
      return asset;
    });
  cachedPromise.catch(() => {
    cachedPromise = null;
    setFetchState({ status: 'error' });
  });
  return cachedPromise;
}
